version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}

